# Generated by Django 4.0.4 on 2022-05-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recovery_login',
            field=models.BooleanField(default=False),
        ),
    ]
